# APPLICATION CONFIG
spring.application.name=Payment System
server.servlet.context-path=/api

# JPA/HIBERNATE (defaults)
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true

# LIQUIBASE (if you're using it)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# LOGGING
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# PROFILE ACTIVATION
spring.profiles.active=dev