# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/payment_system
spring.datasource.username=payment_user
spring.datasource.password=c7YyDzq)wo0[b9iv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port (optional, default is 8080)
server.port=8080
jwt.secret=G)vU:UE7<q87
